name: period_tracker
description: A period tracking app with AI assistant
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Animations
  google_fonts: ^6.1.0
  # lottie: ^3.0.0  # موقتاً حذف شده
  table_calendar: ^3.0.9
  fl_chart: ^0.66.0
  smooth_page_indicator: ^1.1.0
  
  # State Management
  flutter_riverpod: ^2.4.9
  equatable: ^2.0.5
  
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  
  # API & Network
  dio: ^5.4.0
  google_generative_ai: ^0.1.0
  
  # Audio & Speech
  speech_to_text: ^6.5.0
  flutter_tts: ^3.8.3
  
  # Utilities
  intl: ^0.18.1
  permission_handler: ^11.1.0
  # flutter_local_notifications: ^16.3.0  # موقتاً حذف شده
  path_provider: ^2.1.1
  
  # Icons & Images
  # flutter_svg: ^2.0.9  # موقتاً حذف شده

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  # hive_generator: ^2.0.1  # موقتاً حذف شده
  # build_runner: ^2.4.7  # موقتاً حذف شده

flutter:
  uses-material-design: true
  
  # assets section removed completely
  # assets:
  #   - assets/animations/
  #   - assets/images/
  #   - assets/icons/
